steps:
  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/$PROJECT_ID/imageview:blue', './blue']
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/imageview/imageview:blue', './blue']
  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/$PROJECT_ID/imageview:green', './green']
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/imageview/imageview:green', './green']
images: ['asia-northeast1-docker.pkg.dev/$PROJECT_ID/imageview/imageview:blue', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/imageview/imageview:green']
