apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-blue
spec:
  replicas: 1

  selector:
    matchLabels:
      app: webserver
      color: blue

  template:
    metadata:
      labels:
        app: webserver
        color: blue

    spec:
      containers:
      - name: webserver-container
        image: asia-northeast1-docker.pkg.dev/docker-book-495112/imageview/imageview:blue
        ports:
        - containerPort: 80