apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-green
spec:
  replicas: 1

  selector:
    matchLabels:
      app: webserver
      color: green

  template:
    metadata:
      labels:
        app: webserver
        color: green

    spec:
      containers:
      - name: webserver-container
        image: asia-northeast1-docker.pkg.dev/docker-book-495112/imageview/imageview:green
        ports:
        - containerPort: 80